<?php
?>
<script src="js/usuario.js" type="text/javascript"></script>
<div class="center_content">
    <h1>Conductores</h1>
    <div id="local-nav"><a href="?sec=configuracion&ssec=conductor&op=add"><img src="img/add.png" border="0"/>Agregar Conductor</a></div>
    <div class="bloque">
        <? if(count($cp->getCSec()->getCSec()->usuarios)>0) { ?>
        <table border="0" cellspacing="0" cellpadding="0" width="100%" class="tablarojo">
            <thead>
                <tr>
                    <th align="center">Nombre</th>
                    <th align="center">Rut</th>
                    <th align="center">Telefono</th>
                    <th align="center" width="40">Editar</th>
                    <th align="center" width="40">Eliminar</th>
                </tr>
            </thead>
            <tbody>
                <? foreach($cp->getCSec()->getCSec()->usuarios as $a) {?>
                <tr <?=(!$a->isActive)?"class='deleted'":""?>>
                    <td><?= $a->displayName; ?></td>
                    <td><?= $a->rut; ?></td>
                    <td><?= $a->contactPhone; ?></td>
                    <td align="center"><a href="?sec=configuracion&ssec=conductor&op=mod&id=<?=$a->driverID;?>"><img src="img/page_edit.png" border="0" /></a></td>
                    <td align="center"><a href="?sec=configuracion&ssec=conductor&do=del&id=<?=$a->driverID;?>"><img src="img/delete.png" border="0" /></a></td>
                </tr>
                <? } ?>
            </tbody>
        </table>
        <? } else { ?>
         <p class="mensaje">No hay Conductores</p>
        <? } ?>
    </div>
</div>