<?php
function getSelect($obj, $val, $id, $nom, $sel = null, $style=null, $onChange=null) {
    $r = "<SELECT name='$nom' class='medium-input' style='$style' onChange=\"" . $onChange . "\" id='$nom'>";
    $r .= "<OPTION value = '0'>Ninguno</OPTION>";
    foreach ($obj as $o) {
        if ($sel == $o->$id) {
            $r .= "<OPTION value='" . $o->$id . "' SELECTED>" . $o->$val . "</OPTION>";
        } else {
            $r .= "<OPTION value='" . $o->$id . "'>" . $o->$val . "</OPTION>";
        }
    }
    $r .= "</SELECT>";
    return $r;
}

$error = array("Los cambios fueron guardados correctamente", "Los cambios NO pudieron ser guardados", "El conductor NO pudo ser creado");
if(isset($_GET["e"])) {
    $msg = $error[$_GET["e"]];
    if($_GET["e"]>0) {
        $tipoMsg = "error";
    } else {
        $tipoMsg = "success";
    }
} else {
    if($cp->getCSec()->op == "add_grupo") {
        $msg = "Complete los siguientes campos";
        $tipoMsg = "information";
    } else {
        $msg = "Edite los campos que quiera modificar";
        $tipoMsg = "information";
    }
}
?>
<link rel="stylesheet" type="text/css" href="css/form.css" />
<script src="js/usuario_form.js" type="text/javascript"></script>
<div class="center_content">
    <div id="top-nav">
        <ul>
            <li><a href="?sec=configuracion&ssec=conductor">Volver</a></li>
        </ul>
    </div>
    <h1>Conductores</h1>
    <div class="bloque">
    <h2><?=$cp->getCSec()->getCSec()->tilSec?></h2>
    <form action="?sec=configuracion&ssec=conductor&do=<?=$cp->getCSec()->getCSec()->op?>" method="post" name="formu" id="formu" style="width: 500px;">
        <div class="notification <?=$tipoMsg;?> png_bg">
            <div><?=$msg;?></div>
        </div>
        <p>
            <label>Nombre:</label>
            <input class="text-input medium-input required" type="text" name="nom" value="<?=($cp->getCSec()->getCSec()->obj!=null)?$cp->getCSec()->getCSec()->obj->displayName:""?>" />
            <input type="hidden" name="id" value="<?=($cp->getCSec()->getCSec()->obj!=null)?$cp->getCSec()->getCSec()->obj->driverID:""?>" id="id"/>
            <input type="hidden" name="accountID" value="<?=$cp->getSession()->get("accountID")?>"/>
        </p>
        <div class="clear"></div>
        <p>
            <label>RUT:</label>
            <input class="text-input medium-input required" type="text" name="rut" value="<?=($cp->getCSec()->getCSec()->obj!=null)?$cp->getCSec()->getCSec()->obj->rut:""?>"/>
        </p>
        <div class="clear"></div>
        <p>
            <label>Telefono:</label>
            <input class="text-input medium-input required" type="text" name="tel" value="<?=($cp->getCSec()->getCSec()->obj!=null)?$cp->getCSec()->getCSec()->obj->contactPhone:""?>"/>
        </p>
        <div class="clear"></div>
        <p>
            <label>Vehiculo:</label>
            <?=getSelect($cp->getCSec()->getCSec()->vehiculos, "displayName", "deviceID", "vehiculo", ($cp->getCSec()->getCSec()->dev!=null)?$cp->getCSec()->getCSec()->dev->deviceID:null);?>
        </p>
        <div class="clear"></div>
        <p>
            <label>Estado:</label>
            <?=getSelect($cp->getCSec()->getCSec()->estados, "estado", "id", "estado", ($cp->getCSec()->getCSec()->obj!=null)?$cp->getCSec()->getCSec()->obj->isActive:"");?>
        </p>
        <div class="clear"></div>
        <p>
            <input class="button" type="submit" value="Guardar" />
        </p>
        <div class="clear"></div>
    </form>
    </div>
</div>