<?php ?>
<script src="js/geozona.js" type="text/javascript"></script>
<div class="center_content">
    <h1>Geo Zona</h1>
    <div class="bloque">
        <h2>Todos</h2>
        <div id="local-nav"><a href="?sec=configuracion&ssec=geozona&op=add"><img src="img/add.png" border="0"/>Agregar Geo zona</a></div>
        <? if(count($cp->getCSec()->getCSec()->poligonos)>0) { ?>
        <table border="0" cellspacing="0" cellpadding="0" width="100%" class="tablarojo">
            <thead>
                <tr>
                    <th align="center" width="70">Tipo</th>
                    <th align="center">Nombre</th>
                    <th align="center" width="70">Editar</th>
                    <th align="center" width="70">Eliminar</th>
                </tr>
            </thead>
            <tbody>
            <? foreach ($cp->getCSec()->getCSec()->poligonos as $p) { ?>
                <tr <?=(!$p->ESTADO_POLIGONO)?"class='deleted'":""?>>
                    <td align="center"><img src="http://google.com/mapfiles/ms/t/<?= ($p->ID_TIPO_POLIGONO == 1) ? "Blu" : "Bpu"; ?>.png" border="0" width="20" title="<?= ($p->ID_TIPO_POLIGONO == 1) ? "Geo frontera" : "Geo zona"; ?>"/></td>
                    <td><?= $p->NOM_POLIGONO; ?></td>
                    <td align="center"><a href="?sec=configuracion&ssec=geozona&op=mod&id=<?= $p->ID_POLIGONO; ?>"><img src="img/page_edit.png" border="0" /></a></td>
                    <td align="center"><a href="?sec=configuracion&ssec=geozona&do=del&id=<?= $p->ID_POLIGONO; ?>"><img src="img/delete.png" border="0" /></a></td>
                </tr>
            <? } ?>
            <tbody>
        </table>
        <? } else {?>
        <p class="mensaje">No hay Geozonas</p>
        <? } ?>
    </div>
</div>

