<?php
?>
<script src="js/usuario.js" type="text/javascript"></script>
<div class="center_content">
    <h1>Usuarios</h1>
    <div class="bloque">
        <h2>Todos</h2>
        <div id="local-nav"><a href="?sec=configuracion&ssec=usuario&op=add"><img src="img/add.png" border="0"/>Agregar Usuario</a></div>
        <table border="0" cellspacing="0" cellpadding="0" width="100%" class="tablarojo">
            <thead>
                <tr>
                    <th align="center">Usuario</th>
                    <th align="center">Nombre completo</th>
                    <th align="center">Tipo</th>
                    <th align="center">E-mail</th>
                    <th align="center" width="40">Editar</th>
                    <th align="center" width="40">Eliminar</th>
                </tr>
            </thead>
            <tbody>
                <? foreach($cp->getCSec()->getCSec()->usuarios as $a) {?>
                <tr <?=(!$a->isActive)?"class='deleted'":""?>>
                    <td><?= $a->userName; ?></td>
                    <td><?= $a->contactName; ?></td>
                    <td><?= $a->displayName; ?></td>
                    <td><?= $a->contactEmail; ?></td>
                    <td align="center"><a href="?sec=configuracion&ssec=usuario&op=mod&id=<?=$a->userID;?>"><img src="img/page_edit.png" border="0" /></a></td>
                    <td align="center"><a href="?sec=configuracion&ssec=usuario&do=del&id=<?=$a->userID;?>"><img src="img/delete.png" border="0" /></a></td>
                </tr>
                <? } ?>
            <tbody>
        </table>
    </div>
</div>