<?php
function getSelect($obj, $val, $id, $nom, $sel = null, $style=null, $onChange=null) {
    $r = "<SELECT name='$nom' class='medium-input' style='$style' onChange=\"" . $onChange . "\" id='$nom'>";
    $r .= "<OPTION value = '-1' DISABLED>Seleccionar...</OPTION>";
    foreach ($obj as $o) {
        if ($sel == $o->$id) {
            $r .= "<OPTION value='" . $o->$id . "' SELECTED>" . $o->$val . "</OPTION>";
        } else {
            $r .= "<OPTION value='" . $o->$id . "'>" . $o->$val . "</OPTION>";
        }
    }
    $r .= "</SELECT>";
    return $r;
}

$error = array("Los cambios fueron guardados correctamente", "Los cambios NO pudieron ser guardados", "El usuario NO pudo ser creado");
if(isset($_GET["e"])) {
    $msg = $error[$_GET["e"]];
    if($_GET["e"]>0) {
        $tipoMsg = "error";
    } else {
        $tipoMsg = "success";
    }
} else {
    if($cp->getCSec()->op == "add_grupo") {
        $msg = "Complete los siguientes campos";
        $tipoMsg = "information";
    } else {
        $msg = "Edite los campos que quiera modificar";
        $tipoMsg = "information";
    }
}
?>
<link rel="stylesheet" type="text/css" href="css/form.css" />
<script src="js/usuario_form.js" type="text/javascript"></script>
<div class="center_content">
    <div id="top-nav">
        <ul>
            <li><a href="?sec=configuracion&ssec=usuario">Volver</a></li>
        </ul>
    </div>
    <h1>Usuarios</h1>
    <div class="bloque">
    <h2><?=$cp->getCSec()->getCSec()->tilSec?></h2>
    <form action="?sec=configuracion&ssec=usuario&do=<?=$cp->getCSec()->getCSec()->op?>" method="post" name="formu" id="formu" style="width: 500px;">
        <div class="notification <?=$tipoMsg;?> png_bg">
            <div><?=$msg;?></div>
        </div>
        <p>
            <label>Usuario:</label>
            <input class="text-input medium-input required" type="text" name="user" value="<?=($cp->getCSec()->getCSec()->obj!=null)?$cp->getCSec()->getCSec()->obj->userName:""?>" <?=($cp->getCSec()->getCSec()->obj!=null)?"DISABLED":""?>/>
            <input type="hidden" name="id" value="<?=($cp->getCSec()->getCSec()->obj!=null)?$cp->getCSec()->getCSec()->obj->userID:""?>" id="userID"/>
            <input type="hidden" name="accountID" value="<?=$cp->getSession()->get("accountID")?>"/>
        </p>
        <div class="clear"></div>
        <p>
            <label>Contrase&ntilde;a:<?if($cp->getCSec()->getCSec()->obj!=null) {?><span class="tooltip">Solo si desea cambiarla</span><? } ?></label>
            <input class="text-input medium-input <?=($cp->getCSec()->getCSec()->obj!=null)?"":"required"?>" type="password" name="pass" value=""/>
        </p>
        <div class="clear"></div>
        <p>
            <label>Nombre Completo:</label>
            <input class="text-input medium-input required" type="text" name="nom" value="<?=($cp->getCSec()->getCSec()->obj!=null)?$cp->getCSec()->getCSec()->obj->contactName:""?>"/>
        </p>
        <div class="clear"></div>
        <p>
            <label>E-mail:</label>
            <input class="text-input medium-input required" type="text" name="ema" value="<?=($cp->getCSec()->getCSec()->obj!=null)?$cp->getCSec()->getCSec()->obj->contactEmail:""?>"/>
        </p>
        <div class="clear"></div>
        <p>
            <label>Tipo de usuario:</label>
            <?=getSelect($cp->getCSec()->getCSec()->roles, "DisplayName", "roleID", "rol", ($cp->getCSec()->getCSec()->obj!=null)?$cp->getCSec()->getCSec()->obj->roleID:"");?>
        </p>
        <div class="clear"></div>
        <p>
            <label>Estado:</label>
            <?=getSelect($cp->getCSec()->getCSec()->estados, "estado", "id", "estado", ($cp->getCSec()->getCSec()->obj!=null)?$cp->getCSec()->getCSec()->obj->isActive:"");?>
        </p>
        <div class="clear"></div>
        <? if($cp->getCSec()->getCSec()->op == "mod" && $cp->getCSec()->getCSec()->obj->roleID == 2) { ?>
        <p>
            <label>Grupos de vehiculos:</label>
            <?=getSelect($cp->getCSec()->getCSec()->grupos, "displayName", "groupID", "grupo");?>
            <a onClick="addUserGrupo(); return false;" style="cursor:pointer;"><img src="img/add.png" border="0" title="Asignar grupo" alt="Asignar grupo"/></a>
        </p>
        <div class="elementos" id="grupos">
            <? foreach($cp->getCSec()->getCSec()->userGr as $gr) { ?>
            <div class="elemento medium-input" id="<?=$gr->groupListID?>">
                <a href="?sec=configuracion&ssec=vehiculo&op=mod_grupo&id=<?=$gr->groupID?>"><?=$gr->displayName?></a><a onClick="delUserGrupo(<?=$gr->groupListID?>); return false;" style="cursor:pointer; position: absolute; right: 0;"><img src="img/delete.png" border="0" title="Quitar grupo" alt="Quitar grupo"/></a>
            </div>
            <? } ?>
        </div>
        <div class="clear"></div>
        <? } ?>
        <p>
            <input class="button" type="submit" value="Guardar" />
        </p>
        <div class="clear"></div>
    </form>
    </div>
</div>