<?php
?>
<script src="http://maps.google.com/maps/api/js?sensor=true" type="text/javascript"></script>
<script src="js/jquery.jeditable.js" type="text/javascript"></script>
<script src="js/vehiculos.js" type="text/javascript"></script>
<div class="center_content">
    <h1>Veh&iacute;culos y Grupos</h1>
    <div id="local-nav"><a href="?sec=configuracion&ssec=vehiculo&op=add_grupo"><img src="img/add.png" border="0"/>Agregar Grupo</a></div>
    <div class="bloque">
        <h2>Grupos</h2>
        <? if(count($cp->getCSec()->getCSec()->grupos)>0) { ?>
        <table border="0" cellspacing="0" cellpadding="0" width="100%" class="tablarojo">
            <thead>
                <tr>
                    <th align="center" width="100">Nombre</th>
                    <th align="center">Descripci&oacute;n</th>
                    <th align="center" width="80">N&deg; Vehiculos</th>
                    <th align="center" width="40">Editar</th>
                    <th align="center" width="40">Eliminar</th>
                </tr>
            </thead>
            <tbody>
                <? foreach($cp->getCSec()->getCSec()->grupos as $a) {?>
                <tr <?=(!$a->isActive)?"class='deleted'":""?>>
                    <td align="center"><?= $a->displayName; ?></td>
                    <td><?= $a->description; ?></td>
                    <td align="center"><?= $cp->getCSec()->getCSec()->getNumDevice($a->groupID)->TOTAL; ?></td>
                    <td align="center"><a href="?sec=configuracion&ssec=vehiculo&op=mod_grupo&id=<?=$a->groupID;?>"><img src="img/page_edit.png" border="0" /></a></td>
                    <td align="center"><a href="?sec=configuracion&ssec=vehiculo&do=del_grupo&id=<?=$a->groupID;?>"><img src="img/delete.png" border="0" /></a></td>
                </tr>
                <? } ?>
            <tbody>
        </table>
        <? } else { ?>
            <p class="mensaje">No hay grupos</p>
        <? } ?>
    </div>
    <div class="bloque">
        <h2>Veh&iacute;culos</h2>
        <table border="0" cellspacing="0" cellpadding="0" width="100%" class="tablarojo">
            <thead>
                <tr>
                    <th align="center" width="150">Nombre a mostrar</th>
                    <th align="center" width="100">Patente</th>
                    <th align="center" width="100">Conductor</th>
                    <th align="center" width="100">IMEI</th>
                    <th align="center">&Uacute;ltima posici&oacute;n</th>
                    <th align="center" width="150">Fecha</th>
<!--                    <th align="center" width="40">Editar</th>
                    <th align="center" width="40">Eliminar</th>-->
                </tr>
            </thead>
            <tbody>
                <? $i=0; ?>
                <? foreach($cp->getCSec()->getCSec()->device as $a) {?>
                <tr>
                    <td align="center"><span class="edit" id="<?=$a->deviceID;?>"><?= $a->displayName; ?></span></td>
                    <td align="center"><?= $a->licensePlate; ?></td>
                    <td align="center"><span class="driveEdit" id="dr_<?=$a->driverID?>"><?= $cp->getCSec()->getCSec()->condSel[$a->driverID] ?></span></td>
                    <td align="center"><?= $a->imeiNumber; ?></td>
                    <td class="posicion" id="pos_<?=$i?>"><?= $a->latitude.",".$a->longitude; ?></td>
                    <td align="center"><?= $a->fecha ?></td>
<!--                    <td align="center"><a href="?sec=vehiculo&op=mod&id=<?=$a->deviceID;?>"><img src="img/page_edit.png" border="0" /></a></td>
                    <td align="center"><a href="?sec=vehiculo&op=del&id=<?=$a->deviceID;?>"><img src="img/delete.png" border="0" /></a></td>-->
                </tr>
                <? $i++; ?>
                <? } ?>
            </tbody>
        </table>
    </div>
</div>
<script>
    $(".driveEdit").editable(function(value, settings){
//        console.log(this);
//        console.log(value);
//        console.log(settings);
        json = $.parseJSON(settings.data);
//        console.log(json);
        $old = $("#dr_"+value);
        $old.html("Sin conductor");
        $old.attr("id", "dr_0");
        $(this).attr("id", "dr_"+value);
        return json[value];
    },
    {
        data   : '<?php print json_encode($cp->getCSec()->getCSec()->condSel); ?>',
        type: 'select',
        submit: 'Ok'
    }
    );
</script>